wwi21seb-projekt/Client_BubbleMatee

package.json, scanFolderForLongFiles.cjs, src/components/about/carousel-project-participants.svelte, src/components/about/carousel.svelte, src/components/index.ts
This Pull-Request is just adding a script that helps to automate pr reviews by checking the files for the number of lines. It is not part of the source code of the web app. Therefore the checklist is obsolete.
=> Script for number of lines

scanFolderForLongFiles.cjs
=> feat: fix pipeline deepsource

.env, src/app.html, src/components/posts/feed-post-card-elements/feed-post-header.svelte, src/components/profile/profile-header.svelte, src/components/profile/profile-view.svelte, src/domains/ServerResponses.ts, src/domains/index.ts, src/hooks.server.ts, src/routes/(app)/(protected)/myProfile/+page.svelte, src/routes/(app)/(protected)/myProfile/settings/changePassword/+page.svelte, src/routes/(app)/(protected)/myProfile/settings/editProfileInformation/+page.svelte, src/routes/(app)/(protected)/search/+page.svelte, src/routes/(app)/login/+page.svelte, src/routes/(app)/login/register/+page.svelte, src/routes/(app)/login/resendToken/+page.svelte, src/routes/(app)/login/verify/+page.svelte, src/routes/api/feed/+server.ts, src/routes/api/imprint/+server.ts, src/routes/api/subscriptions/+server.ts, src/routes/api/users/+server.ts, src/routes/api/users/[username]/+server.ts, src/routes/api/users/[username]/activate/+server.ts, src/routes/api/users/[username]/feed/+server.ts, src/routes/api/users/login/+server.ts, src/utils/apiRequest/loadPosts.ts, src/utils/errorMessages/errorMessages.ts
=> Refresh token

.env.example, README.md, src/components/layoutComponents/navigation-bar-desktop.svelte, src/components/layoutComponents/navigation-bar-mobile.svelte, src/components/postComponent/components/post-button.svelte, src/components/posts/feed.svelte, src/components/profile/follower-list.svelte, src/components/profile/profile-header-bottom.svelte, src/components/profile/profile-view.svelte, src/components/search/post-tab.svelte, src/components/search/search-tabs.svelte, src/components/search/user-tab.svelte, src/hooks.server.ts, src/images/icons/logout-icon.svelte, src/routes/(app)/(protected)/myProfile/settings/+page.svelte, src/routes/(app)/(protected)/myProfile/settings/changePassword/+page.svelte, src/routes/(app)/(protected)/myProfile/settings/editProfileInformation/+page.svelte, src/routes/(app)/(protected)/search/+page.svelte, src/routes/(app)/login/+page.svelte, src/routes/(app)/login/register/+page.svelte, src/routes/(app)/login/resendToken/+page.svelte, src/routes/(app)/login/verify/+page.svelte, src/routes/api/posts/[postId]/+server.ts, src/routes/api/subscriptions/+server.ts, src/routes/api/subscriptions/[subscriptionId]/+server.ts, src/routes/api/users/[username]/activate/+server.ts, src/utils/apiRequest/loadPosts.ts, src/utils/errorMessages/errorMessages.ts
=> error_handling

src/components/posts/feed.svelte, src/components/profile/follower-list.svelte, src/components/profile/profile-header-bottom.svelte, src/components/search/search-tabs.svelte, src/components/search/user-tab.svelte, src/domains/ServerDomains/subscription.ts, src/domains/index.ts, src/routes/(app)/(protected)/search/+page.svelte, src/utils/apiRequest/postSubscriptions.ts, src/utils/index.ts
=> feat: implementation of follow back

src/hooks.server.ts
=> fix: unauthorized route for location API

src/routes/(app)/(protected)/home/notifications/+page.svelte
=> fix english label

src/components/posts/comments/comments-footer.svelte, src/components/posts/feed-post-card-elements/feed-post-footer.svelte, src/components/posts/feed.svelte, src/components/profile/profile-posts.svelte, src/components/profile/profile-view.svelte, src/components/search/post-tab.svelte, src/components/search/search-tabs.svelte, src/domains/ServerResponses.ts, src/domains/index.ts, src/routes/(app)/(protected)/home/+page.server.ts, src/routes/(app)/(protected)/home/+page.svelte, src/routes/(app)/(protected)/home/user/[username]/+page.server.ts, src/routes/(app)/(protected)/home/user/[username]/+page.svelte, src/routes/(app)/(protected)/myProfile/+page.server.ts, src/routes/(app)/(protected)/myProfile/+page.svelte, src/routes/(app)/(protected)/myProfile/user/[username]/+page.server.ts, src/routes/(app)/(protected)/myProfile/user/[username]/+page.svelte, src/routes/(app)/(protected)/search/+page.server.ts, src/routes/(app)/(protected)/search/+page.svelte, src/routes/(app)/(protected)/search/user/[username]/+page.server.ts, src/routes/(app)/(protected)/search/user/[username]/+page.svelte, src/routes/(app)/trending/+page.server.ts, src/routes/(app)/trending/+page.svelte, src/utils/apiRequest/loadPostUser.ts, src/utils/apiRequest/loadPosts.ts, src/utils/index.ts
=> Load Post Refactor

src/components/chats/chat.svelte, src/components/chats/send-message-component.svelte, src/components/layoutComponents/header.svelte, src/routes/(app)/(protected)/home/chats/[chatId]/+page.svelte, src/routes/+layout.svelte, src/stores/index.ts, src/stores/webSocket.ts
=> webSocket correct path and handle unsend messages

src/components/layoutComponents/modal-header.svelte, src/components/posts/comments/comments.svelte, src/components/posts/repost-component.svelte, src/components/profile/follower-list.svelte, src/components/search/user-tab.svelte, src/routes/(app)/(protected)/search/+page.svelte
=> subscription-list

src/components/index.ts, src/components/login/steps/profile-image-input-step.svelte, src/components/postComponent/components/file-input.svelte, src/components/postComponent/components/fileInput/filedropzone.svelte, src/components/postComponent/components/fileInput/image-display.svelte, src/components/postComponent/components/post-button.svelte, src/components/postComponent/components/post-geolocation.svelte, src/components/postComponent/post-component.svelte, src/components/posts/repost-component.svelte, src/images/icons/check-icon.svelte, src/images/icons/photo-icon.svelte, src/images/index.ts, src/routes/(app)/(protected)/myProfile/settings/+page.svelte, src/routes/(app)/(protected)/myProfile/settings/editProfileInformation/+page.svelte, src/routes/(app)/(protected)/myProfile/settings/editProfilePhoto/+page.server.ts, src/routes/(app)/(protected)/myProfile/settings/editProfilePhoto/+page.svelte, src/routes/(app)/login/register/+page.svelte, src/utils/errorMessages/errorMessages.ts, src/utils/globalFunctions/timeCalculations.ts
=> Pictures and week update

src/components/chats/chat-button.svelte, src/components/chats/contact-list.svelte, src/components/chats/send-message-component.svelte, src/components/notifications/notification-button.svelte, src/components/postComponent/post-component.svelte, src/routes/(app)/(protected)/home/+page.svelte, src/routes/(app)/(protected)/home/notifications/+page.svelte, src/routes/(app)/about/+page.svelte, src/routes/(app)/login/passwordForget/+page.svelte, src/routes/(app)/trending/+page.svelte, src/service-worker.js, src/stores/webSocket.ts, src/utils/pushNotifications/pushNotifications.ts
=> Message notifications

src/components/chats/chat-component.svelte, src/components/chats/chat-mobile-header.svelte, src/components/chats/chat.svelte, src/components/chats/contact-list.svelte, src/components/general/nothing-found-component.svelte, src/components/posts/comments/comments.svelte, src/components/posts/feed.svelte, src/components/posts/repost-component.svelte, src/components/search/user-tab.svelte, src/domains/ServerDomains/chats.ts
=> fixes for eyetracking

src/components/chats/chat-component.svelte, src/components/chats/chat.svelte, src/components/chats/send-message-component.svelte, src/components/profile/profile-header.svelte, src/routes/(app)/(protected)/home/chats/[chatId]/+page.svelte, src/routes/(app)/(protected)/home/chats/newChat/[username]/+page.svelte, src/stores/index.ts, src/stores/webSocket.ts
=> Chat error handling

.github/pull_request_template.md, src/components/layoutComponents/navigation-bar-desktop.svelte, src/components/layoutComponents/navigation-bar-mobile.svelte, src/components/postComponent/components/fileInput/filedropzone.svelte, src/components/postComponent/components/textarea.svelte, src/components/posts/feed-post-card.svelte, src/components/posts/feed.svelte, src/components/search/post-tab.svelte, src/components/search/search-tabs.svelte, src/components/search/user-tab.svelte, src/routes/(app)/(protected)/myProfile/settings/+page.svelte, src/routes/(app)/(protected)/myProfile/settings/editProfilePhoto/+page.svelte, src/routes/(app)/(protected)/search/+page.svelte, src/routes/(app)/trending/+page.svelte, src/static/components/about/About.ts, src/utils/apiRequest/loadUser.ts, src/utils/login/userInfoValidation.ts
=> some small fixes

src/routes/(app)/trending/+page.svelte, src/routes/+layout.server.ts, src/routes/api/notifications/[notificationId]/+server.ts, src/routes/api/posts/[postId]/+server.ts, src/routes/api/posts/[postId]/likes/+server.ts, src/routes/api/subscriptions/[subscriptionId]/+server.ts, src/routes/api/users/+server.ts
=> fix some errors and refactor

src/components/chats/chat.svelte, src/components/chats/contact-list.svelte, src/components/postComponent/components/post-button.svelte, src/components/posts/comments/comments.svelte, src/components/posts/feed-post-card.svelte, src/components/profile/follower-list.svelte, src/utils/pushNotifications/pushNotifications.ts
=> Some more fixes

src/routes/(app)/(protected)/notifications/+page.svelte
=> wait for deletion of notification

DockerfileAlpha, DockerfileBeta, compose.yaml, package.json, pnpm-lock.yaml, svelte.config.js
=> changes for productive docker

README.md
=> Improve Docker Build
